### ISSUE TITLE
Unknown docker network

### ISSUE THREAD

**Issue by mueslo** [jupyterhub/dockerspawner#246]
I'm getting the exception `Exception: Unknown docker network 'jupyterhub'. Did you create it with 'docker network create <name>' and did you pass network_mode=<name> in extra_kwargs?`

My `docker-compose.yml` looks as follows, 
```
services:
  jupyterhub:
    build: config/jupyterhub/build/
    hostname: jupyterhub
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /some/dir/config/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
    environment:
      - TZ=Europe/Berlin
      - DOCKER_NETWORK_NAME=jupyterhub
    ports:
      - 8000:8000
    networks:
      - jupyterhub
networks:
  jupyterhub:
    external:
      name: jupyterhub

```

my `jupyterhub_config.py` contains
```
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
import os
network_name = os.environ['DOCKER_NETWORK_NAME']
c.DockerSpawner.network_name = network_name
c.DockerSpawner.extra_host_config = {'network_mode': network_name}
```

And the network was created on the docker host and is joined by the jupyterhub container:

```
$ docker network inspect jupyterhub
[
    {
        "Name": "jupyterhub",
        "Id": "a5b5988062a86a90a07e70149bb5909652fa7916ad14a4833a42c65fa6b21e2b",
        "Created": "2018-07-20T18:49:56.122820709+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.22.0.0/16",
                    "Gateway": "172.22.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "e2d55d3ad00aceac12ac23ff4e1a8b5346d8fa83225063c234bc2d356fefa28a": {
                "Name": "services_jupyterhub_1",
                "EndpointID": "77635a92e50b348ed57c0e5f0c5b3e264090357b631e44cfc3e37ffc79554967",
                "MacAddress": "02:42:ac:16:00:02",
                "IPv4Address": "172.22.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

However the `container_inspect/NetworkSettings/Networks` output from dockerspawner contains:
```
 'Networks': {'bridge': {'IPAMConfig': None, 'Links': None, 'Aliases': None, 'NetworkID': 'a14fa6572af2040b55215e696aeb5250af8d4a5d1617e40a5d8b52c7d2a5ed4a', 'EndpointID': '66f9aae4ca30f65791be610cd244ca79587dc912151df615dad2d98b1a3637be', 'Gateway': '172.17.0.1', 'IPAddress': '172.17.0.2', 'IPPrefixLen': 16, 'IPv6Gateway': '', 'GlobalIPv6Address': '', 'GlobalIPv6PrefixLen': 0, 'MacAddress': '02:42:ac:11:00:02', 'DriverOpts': None}}
```
It joins the `bridge` network which is some other network.

In other words, the spawned single user notebook server does not join the correct/specified docker network.
Any ideas how to get dockerspawner to work correctly?

**EDIT**: Upon some further investigation, the 1.8.1 docker-py documentation says:

> network_mode is available since v1.11 and sets the Network mode for the container ('bridge': creates a new network stack for the container on the Docker bridge, 'none': no networking for this container, 'container:[name|id]': reuses another container network stack, 'host': use the host network stack inside the container **or any name that identifies an existing Docker network**).

while the current docker-py says:
> network_mode (str) –
>
>One of:
>
>    bridge Create a new network stack for the container on on the bridge network.
>    none No networking for this container.
>    container:<name|id> Reuse another container’s network stack.
>    host Use the host network stack.
>
>Incompatible with network.

And the docker documentations say:

> Network mode. Use the same values as the docker client --net parameter, plus the special form service:[service name].
>
>network_mode: "bridge"
network_mode: "host"
network_mode: "none"
network_mode: "service:[service name]"
network_mode: "container:[container name/id]"

So all the examples can't possibly work? The network_mode argument isn't supposed to be a network name according to the up-to-date documentation!

**EDIT 2**: Yeah, simply removing the `c.DockerSpawner.extra_host_config` option fixes it. You should really update your documentation.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

This is the key part of the error message:

> Did you create it with 'docker network create <name>' 

You need to create the network with `docker network create jupyterhub`


This bit:

```yaml
networks:
  jupyterhub:
    external:
      name: jupyterhub
```

means *assume the network jupyterhub already exists* which will only be true if the network has been created first.
