### ISSUE TITLE
Registry support

### ISSUE THREAD

**Issue by vlizanae** [jupyterhub/dockerspawner#287]
It would be nice to be able to run the spawner without having to pull the single user image in all of the nodes.

**Comment by flixr** [comment]
With the latest release 0.11 you can now specify the `pull_policy`. By default it is already set to `IfNotPresent`, so it should be pulled automatically.

However if you need credentials for your registry, they have to be available for the process/user running jupyterhub.
If jupyterhub itself is running in docker e.g. mount your `.docker/config.json` in the container under `/root/.docker/config.json`.

**Comment by jaredvacanti** [comment]
I am using Docker Swarm 18.09-ce (Ubuntu 18.04 LTS) with a private `registry:2`. My jupyterhub stack is deployed using [`--with-registry-auth`](https://docs.docker.com/engine/reference/commandline/stack_deploy/#options) from a manager node.

```
version: '3.7'

services:

  jupyterhub:
    image: registry.example.com/jupyterhub
    hostname: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - swarm_network
    environment:
      - SERVICE_NAME=jupyter-hub
      - DOCKER_NETWORK_NAME=swarm_network
      - DOCKER_NOTEBOOK_IMAGE=registry.example.com/singleuser
    # Ensure that we execute on a Swarm manager
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  swarm_network:
    external: true
```

`DOCKER_NOTEBOOK_IMAGE=registry.example.com/singleuser` is the issue: I'm not guaranteed that jupyterhub is running on the manager node I've deployed from, so it's not always the case that a `config.json` has been written on the host - it may be running on a cluster node that had credentials sent to it via the services API. 

Are there other ways to share these registry credentials with `SwarmSpawner`?
