### ISSUE TITLE
Need more swarm task states in swarmspawner

### ISSUE THREAD

**Issue by cnydw** [jupyterhub/dockerspawner#298]
I am using SwarmSpawner. Got the following error when user ww starts his server.

> jupyterhub     |       File "/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py", line 1017, in start
jupyterhub     |         yield self.start_object()
jupyterhub     |       File "/opt/conda/lib/python3.6/site-packages/dockerspawner/swarmspawner.py", line 266, in start_object
jupyterhub     |         "Service %s not running: %s" % (self.service_name, pformat(status))
jupyterhub     |     RuntimeError: Service jupyter-ww not running: {'Message': 'created',
jupyterhub     |      'PortStatus': {},
jupyterhub     |      'State': 'new',
jupyterhub     |      'Timestamp': '2019-04-17T14:55:24.161622Z'}

The state of the task was NEW when being queried, which is not included in [the three states in swarmspawner](https://github.com/jupyterhub/dockerspawner/blob/9c1efa0e396e4f2b9939fde7dacbe4187ceb4041/dockerspawner/swarmspawner.py#L257) , and hence the error.

According to docker's [documentation](https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/),  NEW, ASSIGNED and ACCEPTED seem valid to be added to [the three states in swarmspawner](https://github.com/jupyterhub/dockerspawner/blob/9c1efa0e396e4f2b9939fde7dacbe4187ceb4041/dockerspawner/swarmspawner.py#L257).

**Comment by bakanov** [comment]
Have the same issue. Does anyone know a workaround?

**Comment by 1krutarth** [comment]
I am also facing the same issue.. what's the workaround to this ?

**Comment by baijingetangzichen** [comment]
@cnydw
.env
`
CONFIGPROXY_AUTH_TOKEN=08168e511a2547629ae10f4e631c647363833acdb408b8f5be277838e3e1a57f`
Dockerfile
```
# this is built by docker-compose
# from the root of this repo
ARG JUPYTERHUB_VERSION=0.9.2
FROM jupyterhub/jupyterhub:${JUPYTERHUB_VERSION}
#install dockerspawner from the current repo
RUN pip install --no-cache dockerspawner==0.11.1
# install dummyauthenticator
RUN pip install --no-cache jupyterhub-dummyauthenticator
# load example configuration
ADD jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
```
docker-compose.yml
```
version: "3"
services:
  proxy:
    env_file: .env
    image: jupyterhub/configurable-http-proxy:3.1.1
    networks:
      - jupyterhub-networ
    # expose the proxy to the world
    ports:
      - "80:8000"
    command:
      - configurable-http-proxy
      - '--error-target'
      - 'http://hub/hub/error'

  hub:
    # build an image with SwarmSpawner and our jupyterhub_config.py
    env_file: .env
    build:
      context: "./"
      dockerfile: "Dockerfile"
    # mount the docker socket
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/jupyterhub:/srv/jupyterhub"
    networks:
      - jupyterhub-networ
networks:
  jupyterhub-networ:
    driver: overlay
```
jupyterhub_config.py
```
# The proxy is in another container
c.ConfigurableHTTPProxy.should_start = False
c.ConfigurableHTTPProxy.api_url = 'http://proxy:8001'
# The answer to question 1
c.JupyterHub.cleanup_servers = False
c.ConfigurableHTTPProxy.auth_token = "CONFIGPROXY_AUTH_TOKEN"

# tell the hub to use Dummy Auth (for testing)
#c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'
# use SwarmSpawner
c.JupyterHub.spawner_class = 'dockerspawner.SwarmSpawner'
# The Hub should listen on all interfaces,
# so user servers can connect
c.JupyterHub.hub_ip = '0.0.0.0'
# this is the name of the 'service' in docker-compose.yml
c.JupyterHub.hub_connect_ip = 'hub'
# this is the network name for jupyterhub in docker-compose.yml
# with a leading 'swarm_' that docker-compose adds
c.SwarmSpawner.network_name = 'swarm_jupyterhub-networ'

# start jupyterlab
c.Spawner.cmd = ["jupyter", "labhub"]

# debug-logging for testing
import logging
c.JupyterHub.log_level = logging.DEBUG
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
pjoin = os.path.join
c.JupyterHub.db_url = 'sqlite:///' + BASE_DIR + '/jupyterhub/jupyterhub.sqlite'
c.JupyterHub.cookie_secret_file = pjoin(
        BASE_DIR, 'jupyterhub/jupyterhub_cookie_secret')
```
question 1:
```
 Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema
```
question 2:
```
if Proxy.should_start is False" % self.__class__.__name__
hub_1    |     ValueError: ConfigurableHTTPProxy.auth_token or CONFIGPROXY_AUTH_TOKEN env is required if Proxy.should_start is False
```
question 3:
```
hub_1    | [E 2019-07-12 03:25:55.468 JupyterHub app:1952]
hub_1    |     Traceback (most recent call last):
hub_1    |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1950, in launch_instance_async
hub_1    |         await self.start()
hub_1    |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1895, in start
hub_1    |         await self.proxy.check_routes(self.users, self._service_map)
hub_1    |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 57, in locked_method
hub_1    |         return await method(*args, **kwargs)
hub_1    |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 297, in check_routes
hub_1    |         routes = await self.get_all_routes()
hub_1    |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 725, in get_all_routes
hub_1    |         resp = await self.api_request('', client=client)
hub_1    |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/proxy.py", line 686, in api_request
hub_1    |         result = await client.fetch(req)
hub_1    |     tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
hub_1    |     
hub_1    | [D 2019-07-12 03:25:55.469 JupyterHub application:647] Exiting application: jupyterhub
proxy_1  | 03:25:55.473 - warn: [ConfigProxy] 403 GET /api/routes 
```
Can I see the configuration of your specific files?
